import { useState } from 'react';
import { Copy, Check, Mail, MessageCircle, Send, Film, ExternalLink, Clock } from 'lucide-react';
import { g, ff, TEAL, URL_, STXT } from '../constants/index.js';
import { CAPS } from '../data/index.js';
import { track } from '../utils/track.js';
import { Btn } from './ui/index.js';
import { InstagramIcon as Instagram } from './ui/index.js';

export function ShareC({ cp, onShare, onEmailSubmit }) {
  const [cpd, sCPD] = useState(null);
  const [remEmail, setRemEmail] = useState(""); const [remSent, setRemSent] = useState(false);
  const remValid = remEmail.includes("@") && remEmail.includes(".");
  const sh = [{ l: "Copy link", i: <Copy size={13} />, a: () => { cp(URL_); if (onShare) onShare('copy'); } }, { l: "𝕏", i: <span style={{ fontWeight: 800, fontSize: 12 }}>𝕏</span>, a: () => { window.open("https://twitter.com/intent/tweet?text=" + encodeURIComponent(STXT)); if (onShare) onShare('twitter'); } }, { l: "WhatsApp", i: <MessageCircle size={13} />, a: () => { window.open("https://wa.me/?text=" + encodeURIComponent(STXT + " " + URL_)); if (onShare) onShare('whatsapp'); } }, { l: "Telegram", i: <Send size={13} />, a: () => { window.open("https://t.me/share/url?url=" + encodeURIComponent(URL_)); if (onShare) onShare('telegram'); } }, { l: "Facebook", i: <ExternalLink size={13} />, a: () => { window.open("https://www.facebook.com/sharer/sharer.php?u=" + encodeURIComponent(URL_)); if (onShare) onShare('facebook'); } }, { l: "Email", i: <Mail size={13} />, a: () => { window.open("mailto:?subject=Butterfly%20Challenge&body=" + encodeURIComponent(STXT)); if (onShare) onShare('email'); } }];
  return <div style={{ fontFamily: ff }}><p style={{ color: g.t3, fontSize: 14, marginBottom: 16 }}>Share in 10 seconds.</p><div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 6, marginBottom: 18 }}>{sh.map(s => <button key={s.l} onClick={s.a} aria-label={"Share via " + s.l} className="hov-lift" style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 4, padding: "12px 4px", borderRadius: 12, border: "1px solid #e8e8ed", background: "#fff", cursor: "pointer", color: g.t1, fontSize: 11, fontWeight: 500, fontFamily: ff, transition: "all .2s cubic-bezier(.16,1,.3,1)" }}>{s.i}<span>{s.l}</span></button>)}</div><p style={{ fontSize: 12, color: g.t3, marginBottom: 10, display: "flex", alignItems: "center", gap: 4 }}><Instagram size={11} /><Film size={11} />Copy a caption for Instagram & TikTok.</p><div style={{ display: "flex", flexDirection: "column", gap: 6, marginBottom: 18 }}>{CAPS.map(t => <div key={t.id} style={{ border: "1px solid #e8e8ed", borderRadius: 12, padding: 11, transition: "border-color .2s" }}><p style={{ fontSize: 13, color: g.t2, lineHeight: 1.5, marginBottom: 6 }}>{t.text}</p><button aria-label="Copy caption" onClick={() => { navigator.clipboard.writeText(t.text).then(() => { sCPD(t.id); track('share_caption_copied'); setTimeout(() => sCPD(null), 1500); }); }} style={{ background: "none", border: "none", cursor: "pointer", fontSize: 12, fontWeight: 500, color: cpd === t.id ? TEAL : g.t3, display: "flex", alignItems: "center", gap: 3, padding: 0, fontFamily: ff, transition: "color .2s" }}>{cpd === t.id ? <><Check size={10} />Copied</> : <><Copy size={10} />Copy</>}</button></div>)}</div><div style={{ borderTop: "1px solid " + g.bg, paddingTop: 14 }}><div style={{ display: "flex", alignItems: "center", gap: 3, fontSize: 12, fontWeight: 500, color: g.t2, marginBottom: 12 }}><Clock size={13} />Get a reminder for May 1</div><div style={{ display: "flex", gap: 6, marginBottom: 14 }}><input type="email" placeholder="your@email.com" value={remEmail} onChange={e => setRemEmail(e.target.value)} style={{ flex: 1, padding: "8px 12px", borderRadius: 8, border: "1px solid #e8e8ed", fontSize: 13, fontFamily: ff, outline: "none", transition: "border-color .2s" }} /><Btn primary onClick={async () => { if (remValid && onEmailSubmit) { const r = await onEmailSubmit(remEmail); if (r.success) setRemSent(true); } else if (remValid) { setRemSent(true); } }} disabled={!remValid} style={{ padding: "8px 14px", fontSize: 12 }}>Remind Me</Btn></div>{remSent && <p style={{ color: TEAL, fontSize: 12, fontWeight: 500, marginBottom: 12 }}><Check size={11} style={{ verticalAlign: "middle", marginRight: 4 }} />You're on the list!</p>}</div></div>;
}
